Ars/urls.py
from django.conf.urls import url
from .views import (SessionListView,
					SessionView,
					QuestionsView,
					QuestionsDetailView,
					SessionSubmissionview,
					SubmissionView,
					SubmissionDetailsView,
					OptionsView,
					QuestionOptions,
					OptionDetailsView,
					CommentsView,
					QuestionCommentsView,
					GenerateQrCodeView,
					QrCodeDetails,
					TopicDetailView)

app_name = 'Ars'

urlpatterns = [

			url(r'^questions/$',QuestionsView.as_view(),name='questions'),
			url(r'^questions/(?P<pk>[0-9]+)/$',QuestionsDetailView.as_view(),name='questionsdetails'),

			url(r'^submissions/$',SubmissionView.as_view(),name='submissioncreate'),
			url(r'^submissions/(?P<session_pk>[0-9]+)/$',SessionSubmissionview.as_view(),name='sessionsubmissions'),
			url(r'^submission/(?P<pk>[0-9]+)/$',SubmissionDetailsView.as_view(),name='submissiondetails'),

			url(r'^options/$',OptionsView.as_view(),name='optionscreate'),
			url(r'^question/(?P<question_pk>[0-9]+)/options/$',QuestionOptions.as_view(),name='question_options'),
			url(r'^option/(?P<pk>[0-9]+)/$',OptionDetailsView.as_view(),name='optionsdetails'),

			url(r'^qrcodes/$', GenerateQrCodeView.as_view(), name='generateqrcode'),
			url(r'^qrcodes/(?P<qrname>[a-zA-Z0-9_.]+)/$', QrCodeDetails.as_view(), name='qrcode_details'),

			url(r'^comments/$',CommentsView.as_view(),name='commentscreate'),
			url(r'^topic/(?P<question_pk>[0-9]+)/comments/$',QuestionCommentsView.as_view(),name='questioncomments'),
			url(r'^topic/(?P<topic_pk>[0-9]+)/$',TopicDetailView.as_view(),name='topic_details')

]

UserAuth/urls.py
from django.conf.urls import  url
from . import views

app_name = 'UserAuth'

urlpatterns=[
		url(r'^$',views.index,name='index'),
		url(r'^signup/$',views.signupview, name='signup'),
		url(r'^logout/$',views.logoutview, name='logout')

]

ars_backend/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls import  url
from Ars.views import userApiView,LoginApiView,userDetailApiView,SessionListView,SessionView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('UserAuth.urls')),
    path('moderator/',include('moderator.urls')),
    path('api/<str:session_key>/',include('Ars.urls')),
    re_path(r'^api/sessions/$',SessionListView.as_view(),name='sessions'),
    re_path(r'^api/sessions/(?P<pk>[0-9]+)/$',SessionView.as_view(),name='sessionsview'),
    re_path(r'^api/users/$',userApiView.as_view(),name='users'),
    re_path(r'^api/users/(?P<pk>[0-9]+)/$',userDetailApiView.as_view(),name='userdetails'),
    re_path(r'^api/login/$',LoginApiView.as_view(),name='login')
]

UserAuth/models.py
from django.db import models

# Create your models here.

UserAuth/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Ars.decorators import Get_check
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from Ars.Serializers import UserSerializer
from rest_framework import status
# Create your views here.

def index(request):
	if request.method=='GET':
		context = {}
		return render(request,"UserAuth/index.html",context)

	elif request.method=='POST':
		context={}
		username=request.POST['username']
		password=request.POST['password']

		user = authenticate(request,username=username,password=password)
		if user is not None:
			login(request,user)
			return HttpResponseRedirect(reverse('moderator:index'))
		else:
			return render(request,"UserAuth/index.html",context,status=status.HTTP_400_BAD_REQUEST)


def signupview(request):
	if request.method=='GET':
		context={}
		return render(request,"UserAuth/signup.html",context)

	elif request.method == 'POST':
		context={}
		username = request.POST['name']
		email=request.POST['email']
		password = request.POST['password']
		password_confirm = request.POST['re_password']
		if password == password_confirm:
			userdata={
					'username':username,
					'email':email,
					'password':password
			}
			serializer_class = UserSerializer(data=userdata)
			if serializer_class.is_valid():
				serializer_class.save()
				print("signup successful!")
				return HttpResponseRedirect(reverse('UserAuth:index'))
			context['errors'] = serializer_class.errors
			print(context)
			return render(request,"UserAuth/signup.html",context)
		return render(request,"UserAuth/signup.html",context)

@Get_check
@login_required
def logoutview(request):
	logout(request)
	return HttpResponseRedirect(reverse('UserAuth:index'))

UserAuth/templates/UserAuth/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	  {% load staticfiles %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'UserAuth/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'UserAuth/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'UserAuth/fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'UserAuth/fonts/iconic/css/material-design-iconic-font.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'UserAuth/vendor/animate/animate.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'UserAuth/vendor/css-hamburgers/hamburgers.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'UserAuth/vendor/animsition/css/animsition.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'UserAuth/vendor/select2/select2.min.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=" {% static 'UserAuth/vendor/daterangepicker/daterangepicker.css'%}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'UserAuth/css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'UserAuth/css/main.css'%}">
<!--===============================================================================================-->
</head>
<body>
	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'UserAuth/images/bg-01.jpg' %}');">
			<div class="wrap-login100">
					{% include 'moderator/partials/success.html' %}
				<form class="login100-form validate-form" method="post" action="">
					{% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="username" placeholder="Username" required>
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="password" placeholder="Password" required>
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>
					<div class="contact100-form-checkbox">
						<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
						<label class="label-checkbox100" for="ckb1">
							Remember me
						</label>
					</div>
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Sign In
						</button>
					</div>
										<div class="text-center p-t-90">
						<a class="txt1" href="{% url 'UserAuth:signup' %}">
							Don't have an account? Signup
						</a>
					</div>

					<div class="text-center p-t-90">
						<a class="txt1" href="#">
							Forgot Password?
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'UserAuth/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'UserAuth/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'UserAuth/vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'UserAuth/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'UserAuth/vendor/select2/select2.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'UserAuth/vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{% static 'UserAuth/vendor/daterangepicker/daterangepicker.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'UserAuth/vendor/countdowntime/countdowntime.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'UserAuth/js/main.js' %}"></script>

</body>
</html>

UserAuth/templates/UserAuth/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'Signup/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'Signup/css/style.css' %}">
</head>
<body>

    <div class="main">

        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container">
                <div class="signup-content">
                    <form method="POST" id="signup-form" class="signup-form" action="">
                        {% csrf_token %}
                        <h2 class="form-title">Create account</h2>
                        <div class="form-group">
                            <input type="text" class="form-input" required name="name" id="name" placeholder="Username"/>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-input" required name="email" id="email" placeholder="Email"/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" required name="password" id="password" placeholder="Password"/>
                            <span toggle="#password" class="zmdi zmdi-eye field-icon toggle-password"></span>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-input" required name="re_password" id="re_password" placeholder="Repeat your password"/>
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                            <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="Sign up"/>
                        </div>
                    </form>
                    <p class="loginhere">
                        Have already an account ? <a href="{% url 'UserAuth:index' %}" class="loginhere-link">Login here</a>
                    </p>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'Signup/vendor/jquery/jquery.min.js' %} "></script>
    <script src="{% static 'Signup/js/main.js' %}"></script>
</body>
</html>