Ars/urls.py
from django.conf.urls import url
from .views import (SessionListView,
					SessionView,
					QuestionsView,
					QuestionsDetailView,
					SessionSubmissionview,
					SubmissionView,
					SubmissionDetailsView,
					OptionsView,
					QuestionOptions,
					OptionDetailsView,
					CommentsView,
					QuestionCommentsView,
					GenerateQrCodeView,
					QrCodeDetails,
					TopicDetailView)

app_name = 'Ars'

urlpatterns = [

			url(r'^questions/$',QuestionsView.as_view(),name='questions'),
			url(r'^questions/(?P<pk>[0-9]+)/$',QuestionsDetailView.as_view(),name='questionsdetails'),

			url(r'^submissions/$',SubmissionView.as_view(),name='submissioncreate'),
			url(r'^submissions/(?P<session_pk>[0-9]+)/$',SessionSubmissionview.as_view(),name='sessionsubmissions'),
			url(r'^submission/(?P<pk>[0-9]+)/$',SubmissionDetailsView.as_view(),name='submissiondetails'),

			url(r'^options/$',OptionsView.as_view(),name='optionscreate'),
			url(r'^question/(?P<question_pk>[0-9]+)/options/$',QuestionOptions.as_view(),name='question_options'),
			url(r'^option/(?P<pk>[0-9]+)/$',OptionDetailsView.as_view(),name='optionsdetails'),

			url(r'^qrcodes/$', GenerateQrCodeView.as_view(), name='generateqrcode'),
			url(r'^qrcodes/(?P<qrname>[a-zA-Z0-9_.]+)/$', QrCodeDetails.as_view(), name='qrcode_details'),

			url(r'^comments/$',CommentsView.as_view(),name='commentscreate'),
			url(r'^topic/(?P<question_pk>[0-9]+)/comments/$',QuestionCommentsView.as_view(),name='questioncomments'),
			url(r'^topic/(?P<topic_pk>[0-9]+)/$',TopicDetailView.as_view(),name='topic_details')

]

ars_backend/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls import  url
from Ars.views import userApiView,LoginApiView,userDetailApiView,SessionListView,SessionView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('UserAuth.urls')),
    path('moderator/',include('moderator.urls')),
    path('api/<str:session_key>/',include('Ars.urls')),
    re_path(r'^api/sessions/$',SessionListView.as_view(),name='sessions'),
    re_path(r'^api/sessions/(?P<pk>[0-9]+)/$',SessionView.as_view(),name='sessionsview'),
    re_path(r'^api/users/$',userApiView.as_view(),name='users'),
    re_path(r'^api/users/(?P<pk>[0-9]+)/$',userDetailApiView.as_view(),name='userdetails'),
    re_path(r'^api/login/$',LoginApiView.as_view(),name='login')
]

moderator/urls.py
from django.conf.urls import url
from . import views,sessionViews, categoryViews, presentationViews

app_name = 'moderator'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sessioncreate/$', sessionViews.sessionCreate, name='sessioncreate'),
    url(r'^session/(?P<session_pk>[0-9]+)/delete/$', sessionViews.delete_session, name='sessiondelete'),
    url(r'^session/(?P<session_pk>[0-9]+)/deactivate/$', sessionViews.stop_session, name='sessionstop'),
    url(r'^session/(?P<pk>[0-9]+)/categorycreate/$', sessionViews.categoryIndex, name='categorycreate'),
    url(r'^session/categorycreate/discussion/$', categoryViews.createTopic, name='topic_create'),
    url(r'^session/categorycreate/question/$', categoryViews.createQuestion, name='question_create'),
    url(r'^session/categorycreate/question/(?P<question_pk>[0-9]+)/options/$', categoryViews.createOptionsIndex, name='createOptionsIndex'),
    url(r'^session/categorycreate/question/options/$', categoryViews.createOptions, name='createOptions'),
    url(r'^session/(?P<session_pk>[0-9]+)/details/$', sessionViews.sessionDetails, name='sessionDetails'),
    url(r'^session/(?P<session_pk>[0-9]+)/topic/delete/(?P<pk>[0-9]+)/$', categoryViews.deleteTopic, name='topicDelete'),
    url(r'^session/(?P<session_pk>[0-9]+)/question/delete/(?P<pk>[0-9]+)/$', categoryViews.deleteQuestion, name='questionDelete'),
    url(r'^session/category/presentations/(?P<name>[a-zA-Z0-9_.]+)/$', presentationViews.viewPresentation, name='viewPresentation'),
    url(r'^session/presentations/(?P<name>[a-zA-Z0-9_.]+)/$', presentationViews.getPresentation, name='getPresentation')
]

moderator/models.py
from django.db import models

# Create your models here.

moderator/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Ars.decorators import Get_check
from Ars.models import Session
# Create your views here.


@Get_check
@login_required
def index(request):
    context = {}
    current_user_id=request.user.id
    user_sessions = Session.objects.filter(owner=current_user_id)
    context['sessions']=user_sessions
    inactive_session_count = user_sessions.filter(status="stopped").count()
    active_session_count = user_sessions.filter(status='running').count()
    context['active_count']=active_session_count
    context['inactive_count']=inactive_session_count
    # print(context)
    return render(request, 'moderator/index.html', context)

moderator/templates/moderator/modals/createoption_modal.html
<!-- Modal -->
<div class="modal fade" id="createoption_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header row">
        <h5 class="modal-title col-lg-6" id="exampleModalLabel1"> Set Option </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <hr>
        </div>
        <form class="form-sample" id="new_optionform" action="" method="post">
          {% csrf_token %}
                          <!-- <input type="hidden" name="session_pk" value="{{session_pk}}"> -->
          <div class="row">
              <div class="col-md-12">
                <div class="form-group row">
                  <label class="col-md-3 col-form-label">Option<span class="text-danger">*</span></label>
                  <div class="col-md-9">
                    <input type="text" class="form-control" placeholder="option" name="new_option" required>
                  </div>
                </div>
              </div>
          </div>
            <div class="row">
            <div class="col-md-8">
              <div class="form-group row">
                <div class="col-sm-9 offset-3">
                  <input type="submit" class="btn btn-success pull-right" value="Add">
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

moderator/templates/moderator/modals/createpollquestion.html
<!-- Modal -->
<div class="modal fade" id="createpollquestion_Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header row">
        <h5 class="modal-title col-lg-6" id="exampleModalLabel1">Set New Poll </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <hr>
        </div>
        <form class="form-sample" action="{% url 'moderator:question_create' %}" method="post">
          {% csrf_token %}
          <div class="row">
              <div class="col-md-12">
                <input type="hidden" name="session_pk" value="{{session_pk}}">
                <div class="form-group row">
                  <label class="col-md-3 col-form-label">Question<span class="text-danger">*</span></label>
                  <div class="col-md-9">
                    <textarea class="form-control" name="question" placeholder="Question.." rows="8" cols="80" required></textarea>
                    <!-- <input type="message" class="form-control" placeholder="session name" name="session_name" required> -->
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group row">
                  <label class="col-md-3 col-form-label">Choice Type<span class="text-danger">*</span></label>
                  <div class="col-md-9">
                    <select class="form-control" name="option_type" placeholder="Select Options Type--" required>
                      <option value="Single">Single Choice</option>
                      <option value="Multiple">Multiple Choices</option>
                    </select>
                    <!-- <input type="message" class="form-control" placeholder="session name" name="session_name" required> -->
                  </div>
                </div>
              </div>
          </div>
            <div class="row">
            <div class="col-md-8">
              <div class="form-group row">
                <div class="col-sm-9 offset-3">
                  <input type="submit" class="btn btn-success pull-right" value="Submit">
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

moderator/templates/moderator/modals/createsession_modal.html
<!-- Modal -->
<div class="modal fade" id="createsession_Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header row">
        <h5 class="modal-title col-lg-6" id="exampleModalLabel1">Create New Session</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <hr>
        </div>
        <form class="form-sample" action="{% url 'moderator:sessioncreate' %}" method="post">
          {% csrf_token %}
          <div class="row">
              <div class="col-md-10">
                <div class="form-group row">
                  <label class="col-sm-3 col-form-label">Session Name<span class="text-danger">*</span></label>
                  <div class="col-sm-7">
                    <input type="text" class="form-control" placeholder="session name" name="session_name" required>
                  </div>
                </div>
              </div>
          </div>
            <div class="row">
            <div class="col-md-8">
              <div class="form-group row">
                <div class="col-sm-9 offset-3">
                  <input type="submit" class="btn btn-primary pull-right" value="Submit">
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

moderator/templates/moderator/modals/createtopicquestion.html
<!-- Modal -->
<div class="modal fade" id="createtopicquestion_Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header row">
        <h5 class="modal-title col-lg-6" id="exampleModalLabel1">Set New Topic </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <hr>
        </div>
        <form class="form-sample" action="{% url 'moderator:topic_create' %}" method="post">
          {% csrf_token %}
          <div class="row">
              <div class="col-md-12">
                <input type="hidden" name="session_pk" value="{{session_pk}}">
                <div class="form-group row">
                  <label class="col-md-3 col-form-label">Topic<span class="text-danger">*</span></label>
                  <div class="col-md-9">
                    <textarea class="form-control" name="topic" placeholder="Topic for discussion.." rows="8" cols="80" required></textarea>
                    <!-- <input type="message" class="form-control" placeholder="session name" name="session_name" required> -->
                  </div>
                </div>
              </div>
          </div>
            <div class="row">
            <div class="col-md-8">
              <div class="form-group row">
                <div class="col-sm-9 offset-3">
                  <input type="submit" class="btn btn-success pull-right" value="Submit">
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>