Ars/urls.py
from django.conf.urls import url
from .views import (SessionListView,
					SessionView,
					QuestionsView,
					QuestionsDetailView,
					SessionSubmissionview,
					SubmissionView,
					SubmissionDetailsView,
					OptionsView,
					QuestionOptions,
					OptionDetailsView,
					CommentsView,
					QuestionCommentsView,
					GenerateQrCodeView,
					QrCodeDetails,
					TopicDetailView)

app_name = 'Ars'

urlpatterns = [

			url(r'^questions/$',QuestionsView.as_view(),name='questions'),
			url(r'^questions/(?P<pk>[0-9]+)/$',QuestionsDetailView.as_view(),name='questionsdetails'),

			url(r'^submissions/$',SubmissionView.as_view(),name='submissioncreate'),
			url(r'^submissions/(?P<session_pk>[0-9]+)/$',SessionSubmissionview.as_view(),name='sessionsubmissions'),
			url(r'^submission/(?P<pk>[0-9]+)/$',SubmissionDetailsView.as_view(),name='submissiondetails'),

			url(r'^options/$',OptionsView.as_view(),name='optionscreate'),
			url(r'^question/(?P<question_pk>[0-9]+)/options/$',QuestionOptions.as_view(),name='question_options'),
			url(r'^option/(?P<pk>[0-9]+)/$',OptionDetailsView.as_view(),name='optionsdetails'),

			url(r'^qrcodes/$', GenerateQrCodeView.as_view(), name='generateqrcode'),
			url(r'^qrcodes/(?P<qrname>[a-zA-Z0-9_.]+)/$', QrCodeDetails.as_view(), name='qrcode_details'),

			url(r'^comments/$',CommentsView.as_view(),name='commentscreate'),
			url(r'^topic/(?P<question_pk>[0-9]+)/comments/$',QuestionCommentsView.as_view(),name='questioncomments'),
			url(r'^topic/(?P<topic_pk>[0-9]+)/$',TopicDetailView.as_view(),name='topic_details')

]

UserAuth/urls.py
from django.conf.urls import  url
from . import views

app_name = 'UserAuth'

urlpatterns=[
		url(r'^$',views.index,name='index'),
		url(r'^signup/$',views.signupview, name='signup'),
		url(r'^logout/$',views.logoutview, name='logout')

]

ars_backend/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls import  url
from Ars.views import userApiView,LoginApiView,userDetailApiView,SessionListView,SessionView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('UserAuth.urls')),
    path('moderator/',include('moderator.urls')),
    path('api/<str:session_key>/',include('Ars.urls')),
    re_path(r'^api/sessions/$',SessionListView.as_view(),name='sessions'),
    re_path(r'^api/sessions/(?P<pk>[0-9]+)/$',SessionView.as_view(),name='sessionsview'),
    re_path(r'^api/users/$',userApiView.as_view(),name='users'),
    re_path(r'^api/users/(?P<pk>[0-9]+)/$',userDetailApiView.as_view(),name='userdetails'),
    re_path(r'^api/login/$',LoginApiView.as_view(),name='login')
]

moderator/urls.py
from django.conf.urls import url
from . import views,sessionViews, categoryViews, presentationViews

app_name = 'moderator'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sessioncreate/$', sessionViews.sessionCreate, name='sessioncreate'),
    url(r'^session/(?P<session_pk>[0-9]+)/delete/$', sessionViews.delete_session, name='sessiondelete'),
    url(r'^session/(?P<session_pk>[0-9]+)/deactivate/$', sessionViews.stop_session, name='sessionstop'),
    url(r'^session/(?P<pk>[0-9]+)/categorycreate/$', sessionViews.categoryIndex, name='categorycreate'),
    url(r'^session/categorycreate/discussion/$', categoryViews.createTopic, name='topic_create'),
    url(r'^session/categorycreate/question/$', categoryViews.createQuestion, name='question_create'),
    url(r'^session/categorycreate/question/(?P<question_pk>[0-9]+)/options/$', categoryViews.createOptionsIndex, name='createOptionsIndex'),
    url(r'^session/categorycreate/question/options/$', categoryViews.createOptions, name='createOptions'),
    url(r'^session/(?P<session_pk>[0-9]+)/details/$', sessionViews.sessionDetails, name='sessionDetails'),
    url(r'^session/(?P<session_pk>[0-9]+)/topic/delete/(?P<pk>[0-9]+)/$', categoryViews.deleteTopic, name='topicDelete'),
    url(r'^session/(?P<session_pk>[0-9]+)/question/delete/(?P<pk>[0-9]+)/$', categoryViews.deleteQuestion, name='questionDelete'),
    url(r'^session/category/presentations/(?P<name>[a-zA-Z0-9_.]+)/$', presentationViews.viewPresentation, name='viewPresentation'),
    url(r'^session/presentations/(?P<name>[a-zA-Z0-9_.]+)/$', presentationViews.getPresentation, name='getPresentation')
]

moderator/models.py
from django.db import models

# Create your models here.

moderator/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Ars.decorators import Get_check
from Ars.models import Session
# Create your views here.


@Get_check
@login_required
def index(request):
    context = {}
    current_user_id=request.user.id
    user_sessions = Session.objects.filter(owner=current_user_id)
    context['sessions']=user_sessions
    inactive_session_count = user_sessions.filter(status="stopped").count()
    active_session_count = user_sessions.filter(status='running').count()
    context['active_count']=active_session_count
    context['inactive_count']=inactive_session_count
    # print(context)
    return render(request, 'moderator/index.html', context)

moderator/templates/moderator/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  {% load staticfiles %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Dashboard">
  <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
  <title>Auto Response Sytem</title>
  <!-- Favicons -->
  <link href="{% static 'moderator/img/favicon.png' %}" rel="icon">
  <link href="{% static 'moderator/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'moderator/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!--external css-->
  <link href="{% static 'moderator/lib/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="{% static 'moderator/css/zabuto_calendar.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'moderator/lib/gritter/css/jquery.gritter.css' %}" />

  <link href="{% static 'moderator/lib/advanced-datatable/css/demo_page.css' %} " rel="stylesheet" />
  <link href="{% static 'moderator/lib/advanced-datatable/css/demo_table.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'moderator/lib/advanced-datatable/css/DT_bootstrap.css' %}" />


  <!-- Custom styles for this template -->
  <link href="{% static 'moderator/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'moderator/css/style-responsive.css' %}" rel="stylesheet">
  <style media="screen">
  html {
  background-color: #ffffff;
  /* Or any color / image you want */}
  </style>
  <script src="{% static 'moderator/lib/chart-master/Chart.js' %}"></script>
</head>

<body>
  <section id="container">
    <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
    <!--header start-->
    <header class="header black-bg">
      <div class="sidebar-toggle-box">
        <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
      </div>
      <!--logo start-->
      <a href="index.html" class="logo"><b>AUTO<span> RS</span></b></a>
      <!--logo end-->
      <div class="top-menu">
        <ul class="nav pull-right top-menu">
          <li>{% block fullscreen_btn %}{%endblock%}</li>
          <li><a class="logout" href="{% url "UserAuth:logout" %}">Logout</a></li>
        </ul>
      </div>
      {% include 'moderator/partials/success.html' %}
    </header>
    <!--header end-->
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
          <p class="centered"><a href="profile.html"><img src="{% static 'moderator/img/user.png' %}" class="img-circle" width="80"></a></p>
          <h5 class="centered">{{request.user.username}}</h5>
          <li class="mt">
            <a class="active" href="{%url 'moderator:index'%}">
              <i class="fa fa-dashboard"></i>
              <span>Dashboard</span>
              </a>
          </li>
        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->

    {% block body %}
    {% endblock %}


    <!--main content end-->
    <!--footer start-->
    <footer class="site-footer">
      <div class="text-center">
        <p>
          &copy; Copyrights <strong>sematebrian2067</strong>
          <p>
            @Hubsight . All Rights Reserved
                          <script>
                document.write(new Date().getFullYear())
              </script>
          </p>
        </p>
        <div class="credits">
          <!--
            You are NOT allowed to delete the credit link to TemplateMag with free version.
            You can delete the credit link only if you bought the pro version.
            Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/dashio-bootstrap-admin-template/
            Licensing information: https://templatemag.com/license/
          -->
          <!-- Created with Dashio template by <a href="https://templatemag.com/">TemplateMag</a> -->
        </div>
        <a href="#" class="go-top">
          <i class="fa fa-angle-up"></i>
          </a>
      </div>
    </footer>
    <!--footer end-->
  </section>
  <script src="{% static 'moderator/lib/optionsjs.js' %}" charset="utf-8"></script>
  <!-- js placed at the end of the document so the pages load faster -->
  <script src="{% static 'moderator/lib/jquery/jquery.min.js' %}"></script>

  <script src="{% static 'moderator/lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script class="include" type="text/javascript" src="{% static 'moderator/lib/jquery.dcjqaccordion.2.7.js' %}"></script>
  <script src="{% static 'moderator/lib/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'moderator/lib/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <script src="{% static 'moderator/lib/jquery.sparkline.js' %}"></script>
  <!--common script for all pages-->
  <script src="{% static 'moderator/lib/common-scripts.js' %}"></script>
  <script type="text/javascript" src="{% static 'moderator/lib/gritter/js/jquery.gritter.js' %}"></script>
  <script type="text/javascript" src="{% static 'moderator/lib/gritter-conf.js' %}"></script>
  <!--script for this page-->
  <script src="{% static 'moderator/lib/sparkline-chart.js' %}"></script>
  <script src="{% static 'moderator/lib/zabuto_calendar.js' %}"></script>

  <script type="text/javascript" language="javascript" src="{% static 'moderator/lib/advanced-datatable/js/jquery.js' %}"></script>
  <script type="text/javascript" language="javascript" src="{% static 'moderator/lib/advanced-datatable/js/jquery.dataTables.js' %}"></script>
  <script type="text/javascript" src="{% static 'moderator/lib/advanced-datatable/js/DT_bootstrap.js' %}"></script>
 <!--  <script type="text/javascript">
    $(document).ready(function() {
      var unique_id = $.gritter.add({
        // (string | mandatory) the heading of the notification
        title: 'Welcome to Dashio!',
        // (string | mandatory) the text inside the notification
        text: 'Hover me to enable the Close Button. You can hide the left sidebar clicking on the button next to the logo.',
        // (string | optional) the image to display on the left
        image: 'img/ui-sam.jpg',
        // (bool | optional) if you want it to fade out on its own or just sit there
        sticky: false,
        // (int | optional) the time you want it to be alive for before fading out
        time: 8000,
        // (string | optional) the class name you want to apply to that specific message
        class_name: 'my-sticky-class'
      });

      return false;
    });
  </script> -->

  <script type="application/javascript">
    $(document).ready(function() {
      $("#date-popover").popover({
        html: true,
        trigger: "manual"
      });
      $("#date-popover").hide();
      $("#date-popover").click(function(e) {
        $(this).hide();
      });

      $("#my-calendar").zabuto_calendar({
        action: function() {
          return myDateFunction(this.id, false);
        },
        action_nav: function() {
          return myNavFunction(this.id);
        },
        ajax: {
          url: "show_data.php?action=1",
          modal: true
        },
        legend: [{
            type: "text",
            label: "Special event",
            badge: "00"
          },
          {
            type: "block",
            label: "Regular event",
          }
        ]
      });
    });

    function myNavFunction(id) {
      $("#date-popover").hide();
      var nav = $("#" + id).data("navigation");
      var to = $("#" + id).data("to");
      console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
    }

        /* Formating function for row details */
    function fnFormatDetails(oTable, nTr) {
      var aData = oTable.fnGetData(nTr);
      var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
      sOut += '<tr><td>Rendering engine:</td><td>' + aData[1] + ' ' + aData[4] + '</td></tr>';
      sOut += '<tr><td>Link to source:</td><td>Could provide a link here</td></tr>';
      sOut += '<tr><td>Extra info:</td><td>And any further details here (images etc)</td></tr>';
      sOut += '</table>';

      return sOut;
    }

    $(document).ready(function() {
      /*
       * Insert a 'details' column to the table
       */
      var nCloneTh = document.createElement('th');
      var nCloneTd = document.createElement('td');
      nCloneTd.innerHTML = '<img src="lib/advanced-datatable/images/details_open.png">';
      nCloneTd.className = "center";

      $('#hidden-table-info thead tr').each(function() {
        this.insertBefore(nCloneTh, this.childNodes[0]);
      });

      $('#hidden-table-info tbody tr').each(function() {
        this.insertBefore(nCloneTd.cloneNode(true), this.childNodes[0]);
      });

      /*
       * Initialse DataTables, with no sorting on the 'details' column
       */
      var oTable = $('#hidden-table-info').dataTable({
        "aoColumnDefs": [{
          "bSortable": false,
          "aTargets": [0]
        }],
        "aaSorting": [
          [1, 'asc']
        ]
      });

      /* Add event listener for opening and closing details
       * Note that the indicator for showing which row is open is not controlled by DataTables,
       * rather it is done here
       */
      $('#hidden-table-info tbody td img').live('click', function() {
        var nTr = $(this).parents('tr')[0];
        if (oTable.fnIsOpen(nTr)) {
          /* This row is already open - close it */
          this.src = "lib/advanced-datatable/media/images/details_open.png";
          oTable.fnClose(nTr);
        } else {
          /* Open this row */
          this.src = "lib/advanced-datatable/images/details_close.png";
          oTable.fnOpen(nTr, fnFormatDetails(oTable, nTr), 'details');
        }
      });
    });
  </script>

</body>

</html>

moderator/templates/moderator/createoptions.html
{% extends 'moderator/base.html'%}
{%block body%}

<section id="main-content">
  <section class="wrapper ">
    <div class="row">
      <div class="col-lg-12">
        <div class="col-lg-6 col-md-offset-3 col-md-6 col-sm-6 col-xs-12">
          <div class="custom-box">
            <div class="servicetitle">
              <h4>Question</h4>
              <hr>
              <br>
              <p>{{question}}</p>
              <input type="hidden" id="option_type" value="{{type}}">
            </div>
            <div class="servicetitle">
              <br>
              <h4>Options</h4>
              <hr>
              <br>
            </div>
            <div class="">
              <a href="" data-toggle="modal" data-target="#createoption_modal">
                <span>
                  <i class="fa fa-plus-circle"></i>
                    add option
                </span>
              </a>
            </div>
            <div class="servicetitle">
              <br><br>
            </div>
            <div>
              <form class="form-sample" id="optionsform" action="{% url 'moderator:createOptions' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="question_pk" value="{{question_pk}}">
                <div id="optionsHolder" class="row">

                    <!-- <div class="col-md-12 col-sm-12 col-md-offset-1">
                      <div class="form-group pull-left row">
                        <div class="col-md-1">
                          <input type="checkbox" name="sports[]" value="option2">
                        </div>
                      <label class="col-md-2  col-form-label">Option</label>
                      </div>
                    </div> -->

                </div>
                  <div class="row">
                  <div class="col-md-12 col-md-offset-2">
                    <div class="form-group row">
                      <div class="col-sm-9">
                        <input type="submit" class="pull-left btn btn-theme" value="Done">
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <!-- end custombox -->
        </div>
        <!-- end col-4 -->
      </div>
      <!--  /col-lg-12 -->
    </div>
    <!--  /row -->
    {%include 'moderator/modals/createoption_modal.html' %}
  </section>
  <!-- /wrapper -->
</section>

{%endblock%}

moderator/templates/moderator/index.html
{% extends 'moderator/base.html' %}

{% block body%}
    <section id="main-content">
      <section class="wrapper">
        <div class="row">
          <div class="col-lg-12 main-chart">

            <div class="row mt">
              <!-- SERVER STATUS PANELS -->
              <div class="col-md-3 col-sm-12 mb">
                <div class="grey-panel pn">
                  <div class="grey-header">
                    <h5>SESSIONS</h5>
                  </div>
                  <h1 class="mt fa fa-4x">
                  {%if sessions%}
                      {{sessions.count}}
                  {%else%}
                    0
                  {%endif%}
              </h1>
                  <div class="row">
                    <div class="col-sm-6 col-xs-6 goleft">
                      <p><br/></p>
                    </div>
                   <!--  <div class="col-sm-6 col-xs-6">
                      <h2>21%</h2>
                    </div> -->
                  </div>
                </div>
                <!-- /grey-panel -->
              </div>
              <!-- /col-md-4-->
              <div class="col-md-3 col-sm-12 mb">
                <div class=" green-panel  pn">
                  <div class="green-header ">
                    <h5>ACTIVE SESSIONS</h5>
                  </div>
                                    <h1 class="mt fa fa-4x">
                                      {%if sessions%}
                                      {{active_count}}
                                      {%else%}
                                      0
                                      {%endif%}
                                    </h1>
                  <footer>
                    <div class="pull-left">

                    </div>
                    <div class="pull-right">
                    </div>
                  </footer>
                </div>
                <!--  /darkblue panel -->
              </div>
              <!-- /col-md-4 -->
              <div class="col-md-3 col-sm-12 mb">
                <!-- REVENUE PANEL -->
                <div class="darkblue-panel pn">
                  <div class="darkblue-header">
                    <h5><i class=" fa fa-moon-o"></i> INACTIVE SESSIONS</h5>
                  </div>
                                    <h1 class="mt fa fa-4x">
                                      {%if sessions%}
                                        {{inactive_count}}
                                      {%else%}
                                        0
                                      {%endif%}
                                    </h1>
                  <p class="mt"></p>
                </div>
              </div>

                 <div class="col-md-3 col-sm-12 mb">
                <div class="grey-panel pn">
                  <div class="grey-header">
                    <h5>CREATE SESSION</h5>
                  </div>
                  <a href="" data-toggle="modal" data-target="#createsession_Modal">
                    <h1 class="mt"><i class="fa fa-plus fa-3x"></i></h1>
                  </a>

                  <p>start new session</p>
                  <footer>
                    <div class="centered">
                      <!-- <h5><i class="fa fa-trophy"></i> 17,988</h5> -->
                    </div>
                  </footer>
                </div>
                <!--  /darkblue panel -->
              </div>
              <!-- /col-md-4 -->
            </div>
            <!-- /row -->

        <div class="row mt">
          <div class="col-md-12">
            <div class="content-panel">
              <table class="table table-striped table-advance table-hover">
                <h4><i class="fa fa-angle-right"></i>SESSIONS SUMMARY</h4>
                <hr>
                <thead>
                  <tr>
                    <th>No.</th>
                    <th><i class="fa fa-key"></i>Session Key</th>
                    <!-- <th class="hidden-phone"><i class="fa fa-question-circle"></i>Status</th> -->
                    <th><i class="fa fa-calendar"></i> Created On</th>
                    <th><i class=" fa fa-edit"></i> Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {%if sessions%}
                  {%for session in sessions%}
                  <tr>
                    <td>{{forloop.counter}}</td>
                    <td>
                      <a href="{% url 'moderator:sessionDetails' session.id %}">{{session.session_key}}</a>
                    </td>
                    <td class="hidden-phone">{{session.created_on}}</td>
                    <td><span class="label label-{% if session.status == 'stopped'%}danger{% else %}info{% endif %} label-mini">{{session.status}}</span></td>
                    <td>
                      {%if session.status == "running" %}
                          <a href="{% url 'moderator:categorycreate' session.id %}">
                            <span class="label label-success">
                              <i class="fa fa-plus"></i>
                            </span>
                          </a>
                        <a href="{% url 'moderator:sessionstop' session.id %}">
                          <span class="label label-warning label-mini">Stop</span>
                        </a>
                        {%endif%}
                        <a href="{% url 'moderator:sessiondelete' session.id %}">
                          <span class="label label-danger">
                            <i class="fa fa-trash-o"></i>
                          </span>
                        </a>
                    </td>
                  </tr>
                  {%endfor%}
                  {%endif%}
                </tbody>
              </table>
            </div>
            <!-- /content-panel -->
          </div>
          <!-- /col-md-12 -->
        </div>






            <!-- /row -->

            <!-- /row -->
          </div>
          <!-- /col-lg-9 END SECTION MIDDLE -->
          <!-- **********************************************************************************************************************************************************
              RIGHT SIDEBAR CONTENT
              *********************************************************************************************************************************************************** -->

          <!-- /col-lg-3 -->
        </div>
        <!-- /row -->
      </section>
      {%include 'moderator/modals/createsession_modal.html' %}
    </section>

    {% endblock %}

moderator/templates/moderator/sessiondetails.html
{% extends 'moderator/base.html'%}
{%block body%}

<!--main content start-->
<section id="main-content">
  <section class="wrapper">
    <!-- /row -->
    <div class="row content-panel">
      <h2 class="centered">DISCUSSIONS</h2>
      <div class="col-md-10 col-md-offset-1 mt mb">
        <div class="accordion" id="accordion1">
          {%for topic in topics%}
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseTopic-{{topic.id}}">
                <em class="glyphicon glyphicon-chevron-right icon-fixed-width"></em>{{topic.topic_name}}
                </a>
            </div>
            <div id="collapseTopic-{{topic.id}}" class="accordion-body collapse in">
              <div class="accordion-inner">
                {%if topic.presentation_name is not None %}
                <a href="{% url 'moderator:viewPresentation' topic.presentation_name %}">
                  <h5><i class="fa fa-bar-chart"></i> View Response Presentation</h5>
                </a>
                {% endif %}
                {%if topic.qr_link_name is not None %}
                <a href="{% url 'Ars:qrcode_details' session_key topic.qr_link_name %}">
                  <h5><i class="fa fa-qrcode"></i> View QrCode</h5>
                </a>
                {%endif%}
                <a href="#" onclick="
                var result = confirm('Are you sure you wish to delete this topic?');
                    if( result ){
                            event.preventDefault();
                            document.getElementById('delete-form-topic-{{topic.id}}').submit();
                    }
                        " >
                    <h5><i class="fa fa-trash-o"></i> Delete topic</h5>
                </a>
                <form id="delete-form-topic-{{topic.id}}" action="{% url 'moderator:topicDelete' topic.session.id topic.id %}"
                  method="POST" style="display: none;">
                  {% csrf_token %}
                  <input type="hidden" class="btn btn-xs" name="_method" value="delete">
                  </form>
              </div>
            </div>
          </div>
          {%empty%}
          <p>
            <h4 class="centered">
            Session does not contain any topics yet!!
            </h4>
          </p>
          {%endfor%}
        </div>
        <!-- end accordion -->
      </div>
      <!-- col-md-10 -->
    </div>
    <div class="row">
      <p></p>
    </div>

    <div class="row content-panel">
      <h2 class="centered">POLLS</h2>
      <div class="col-md-10 col-md-offset-1 mt mb">
        <div class="accordion" id="accordion2">
          {%for poll in polls%}
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapsePoll-{{poll.id}}">
                <em class="glyphicon glyphicon-chevron-right icon-fixed-width"></em>{{poll.question}}
                </a>
            </div>
            <div id="collapsePoll-{{poll.id}}" class="accordion-body collapse in">
              <div class="accordion-inner">
                {%if poll.presentation_name is not None %}   
                <a href="{% url 'moderator:viewPresentation' poll.presentation_name %}">
                  <h5><i class="fa fa-bar-chart"></i> View Response Presentation</h5>
                </a>
                {% endif %}
                {%if poll.qr_link_name is not None %}
                <a href="{% url 'Ars:qrcode_details' session_key poll.qr_link_name %}">
                  <h5><i class="fa fa-qrcode"></i> View QrCode</h5>
                </a>
                {%endif%}
                <a href="#" onclick="
                var result = confirm('Are you sure you wish to delete this question?');
                    if( result ){
                            event.preventDefault();
                            document.getElementById('delete-form-poll-{{poll.id}}').submit();
                    }
                        " >
                    <h5><i class="fa fa-trash-o"></i> Delete question</h5>
                </a>
                <form id="delete-form-poll-{{poll.id}}" action="{% url 'moderator:questionDelete' poll.session.id poll.id %}"
                  method="POST" style="display: none;">
                  {% csrf_token %}
                  <input type="hidden" class="btn btn-xs" name="_method" value="delete">
                  </form>
            </div>
            </div>
          </div>
          {%empty%}
          <p>
            <h4 class="centered">
            Session does not contain polls yet!!
            </h4>
          </p>
          {%endfor%}
        </div>
        <!-- end accordion -->
      </div>
      <!-- col-md-10 -->
    </div>
    <div class="row">
      <p></p>
    </div>

    <div class="row content-panel">
      <h2 class="centered">SUBMISSIONS</h2>
      <div class="col-md-10 col-md-offset-1 mt mb">
        <div class="accordion" id="accordion3">
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion3" href="#collapseOne3">
                <em class="glyphicon glyphicon-chevron-right icon-fixed-width"></em>Submissions
                </a>
            </div>
            <div id="collapseOne3" class="accordion-body collapse in">
              <div class="accordion-inner">
                {%for submission in submissions%}
                <a href="#">
                  <h5><i class="fa fa-bar-chart"></i> View Response Presentation</h5>
                </a>
                <a href="#">
                  <h5><i class="fa fa-qrcode"></i> View QrCode</h5>
                </a>
                {%empty%}
                <p>
                  <h4 class="centered">
                  Session does not contain submissions yet!!
                  </h4>
                </p>
                {%endfor%}
            </div>
            </div>
          </div>
        </div>
        <!-- end accordion -->
      </div>
      <!-- col-md-10 -->
    </div>
    <!--  /row -->
  </section>
  <!-- /wrapper -->
</section>
<!-- /MAIN CONTENT -->
<!--main content end-->

{%endblock%}